### ISSUE TITLE
get_name_from_camera_feed not working

### ISSUE THREAD

**Issue by rsingh2083** [GraphtyLove/Face-recognition-project#22]
Hi there,

Also get_name_from_camera_feed.py throws this error : -

```
Traceback (most recent call last):
  File "..\..\..\..\Downloads\Face-recognition-project-master\API\get_name_from_camera_feed.py", line 96, in <module>
    best_match_index = np.argmin(face_distances)
  File "<__array_function__ internals>", line 6, in argmin
  File "C:\Users\SARTHAK\.pyenv\pyenv-win\versions\3.6.8-amd64\lib\site-packages\numpy\core\fromnumeric.py", line 1222, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out)
  File "C:\Users\SARTHAK\.pyenv\pyenv-win\versions\3.6.8-amd64\lib\site-packages\numpy\core\fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
```

**Comment by rsingh2083** [comment]
Strictly works on python3.6

**Comment by rsingh2083** [comment]
Strictly works on python3.6
